#!/bin/bash

# Runs the dockerfile
docker run -it dohtest /bin/bash

#--------------------------------------------------------------------------------------------------
# This section copies the CSV file generated by Dohlyzer from the Docker container to the host
# machine within the "CSV_files" folder after the user exits the container.
#--------------------------------------------------------------------------------------------------
container_id=$(docker ps -l --format "{{.ID}}")
cd CSV_files
docker start $container_id
docker cp $container_id:/code/capture/capturedPackets.csv .
docker stop $container_id

